branches:
  exclude: gh-pages

pipeline:
  build:
    image: gemtest/vaquero-docs:0.1
    commands:
      - ./convert.sh
      
  git_push:
    image: plugins/git-push
    remote_name: origin
    branch: gh-pages
    commit: true
    when:
      branch: convert
